name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout beerproto
        uses: actions/checkout@v2
        with:
          repository: beerproto/beerproto
          path: proto
      - uses: dart-lang/setup-dart@v1
      - run: dart pub global activate protoc_plugin
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true      
      - name: Buf generate
        run: buf generate beerprotoapis --template=buf.gen.dart.yaml
        working-directory: ./proto
      - name: Move beer file
        run: mv ./proto/gen/beerproto/v1/* ./lib
      - run: rm -R ./proto
      - name: Push
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.${{ github.run_number }}.0
          body: CI Release ${{ github.ref }}
          draft: false
          prerelease: false

